#!/bin/sh                                                                                                                                           
cd ~
cd proyectos/tor_service/
figlet torweb
python3 -m http.server --bind 127.0.0.1 8080 & sudo tor
